bugfix: endian.h name conflict
The following build error would occur with recent versions of glibc:
/usr/include/bits/waitstatus.h:80:15: error: duplicate member '__w_retcode'

The cause apparently is a name conflict with the file endian.h in the burrow-owl
tree; the solution is to rename the file.